(function(g){var window=this;var Oxa=function(a,b){return g.Mb(a,b)},Y5=function(a,b,c){a.A.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.C)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.dn(a.A,b,c)},Pxa=function(a,b){var c=[];
g.mk(b,function(d){try{var e=g.co.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.bo(e)&&c.push(d)},a);
return c},Qxa=function(a,b){var c=Pxa(a,b);
(0,g.y)(c,function(d){g.co.prototype.remove.call(this,d)},a)},Rxa=function(a){if(a.Wc){if(a.Wc.locationOverrideToken)return{locationOverrideToken:a.Wc.locationOverrideToken};
if(null!=a.Wc.latitudeE7&&null!=a.Wc.longitudeE7)return{latitudeE7:a.Wc.latitudeE7,longitudeE7:a.Wc.longitudeE7}}return null},Sxa=function(a,b){g.fb(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},Txa=function(a,b){var c=b instanceof g.zc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},b6=function(){},Uxa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Vxa=function(a){if(a.Yd&&"function"==typeof a.Yd)return a.Yd();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},Wxa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Me&&"function"==typeof a.Me)var c=a.Me();else if(a.Yd&&"function"==typeof a.Yd)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Jb(a);d=Vxa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Xxa=function(a,b,c,d){var e=new g.Sm(null,void 0);
a&&g.Tm(e,a);b&&g.Um(e,b);c&&g.Vm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Po[a]=!0;
var c=g.No();c&&c.publish.apply(c,arguments);g.Po[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Pm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Yxa(this,a.capabilities||""),Zxa(this,a.experiments||""))},Yxa=function(a,b){a.capabilities.clear();
(0,g.Ae)(b.split(","),g.Ra(Oxa,$xa)).forEach(function(c){a.capabilities.add(c)})},Zxa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},aya=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bya=function(a){return new e6(a)},cya=function(a){return Array.isArray(a)?(0,g.Jc)(a,bya):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return Array.isArray(a)?"["+(0,g.Jc)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},dya=function(a){return(0,g.Jc)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.cb(a,function(c){return f6(c,b)})},eya=function(){var a=(0,g.Ks)();
a&&Qxa(a,a.o.Fg(!0))},l6=function(){var a=g.Ns("yt-remote-connected-devices")||[];
g.yb(a);return a},fya=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Jc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},gya=function(a){g.Ms("yt-remote-connected-devices",a,86400)},n6=function(){if(m6)return m6;
var a=g.Ns("yt-remote-device-id");a||(a=i6(),g.Ms("yt-remote-device-id",a,31536E3));for(var b=l6(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return m6=d},o6=function(){var a=l6(),b=n6();
g.fb(a,b);g.Ps()&&g.Ab(a,b);a=fya(a);if(g.gb(a))try{g.Dq("remote_sid")}catch(c){}else try{g.Bq("remote_sid",a.join(","),-1)}catch(c){}},hya=function(){return g.Ns("yt-remote-session-browser-channel")},iya=function(){return g.Ns("yt-remote-local-screens")||[]},jya=function(){g.Ms("yt-remote-lounge-token-expiration",!0,86400)},kya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Jc)(iya(),function(d){return d.loungeToken}),c=(0,g.Jc)(a,function(d){return d.loungeToken});
(0,g.zi)(c,function(d){return!g.fb(b,d)})&&jya();
g.Ms("yt-remote-local-screens",a,31536E3)},lya=function(a,b){g.Ms("yt-remote-session-browser-channel",a);
g.Ms("yt-remote-session-screen-id",b);var c=l6(),d=n6();g.fb(c,d)||c.push(d);gya(c);o6()},p6=function(a){a||(g.Os("yt-remote-session-screen-id"),g.Os("yt-remote-session-video-id"));
o6();a=l6();g.lb(a,n6());gya(a)},mya=function(){if(!q6){var a=g.no();
a&&(q6=new g.Xn(a))}return q6?!!q6.get("yt-remote-use-staging-server"):!1},nya=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},oya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},r6=function(a){a.length?pya(a.shift(),function(){r6(a)}):s6()},qya=function(a){return"chrome-extension://"+a+"/cast_sender.js"},pya=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},s6=function(){var a=oya();
a&&a(!1,"No cast extension found")},sya=function(){if(rya){var a=2,b=oya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;pya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",s6,c)}},tya=function(){sya();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);r6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},t6=function(a,b,c){g.z.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Pd=b;this.C=(0,g.x)(this.LF,this);this.o=!1;this.u=0;this.A=this.Ja=null;this.B=[]},u6=function(a,b,c){g.z.call(this);
this.B=null!=c?a.bind(c):a;this.Pd=b;this.A=null;this.o=!1;this.u=0;this.Ja=null},v6=function(a){a.Ja=g.Zf(function(){a.Ja=null;
a.o&&!a.u&&(a.o=!1,v6(a))},a.Pd);
var b=a.A;a.A=null;a.B.apply(null,b)},w6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Uxa(a)},x6=function(){},y6=function(){},uya=function(){},wya=function(a){return(a=vya(a))?new ActiveXObject(a):new XMLHttpRequest},vya=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},z6=function(a,b,c,d){this.o=a;
this.A=b;this.H=c;this.G=d||1;this.C=45E3;this.B=new g.A1(this);this.u=new g.Yf;this.u.setInterval(250)},yya=function(a,b,c){a.ql=1;
a.uh=Z5(b.clone());a.Aj=c;a.F=!0;xya(a,null)},A6=function(a,b,c,d,e){a.ql=1;
a.uh=Z5(b.clone());a.Aj=null;a.F=c;e&&(a.uC=!1);xya(a,d)},xya=function(a,b){a.jl=(0,g.C)();
B6(a);a.oi=a.uh.clone();$5(a.oi,"t",a.G);a.vn=0;a.bd=a.o.Ur(a.o.jn()?b:null);0<a.Rs&&(a.oq=new u6((0,g.x)(a.uD,a,a.bd),a.Rs));a.B.oa(a.bd,"readystatechange",a.UN);var c=a.aj?g.Sb(a.aj):{};a.Aj?(a.Wq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.bd.send(a.oi,a.Wq,a.Aj,c)):(a.Wq="GET",a.uC&&!g.pe&&(c.Connection="close"),a.bd.send(a.oi,a.Wq,null,c));a.o.Gf(1)},Bya=function(a,b,c){for(var d=!0;!a.Ji&&a.vn<c.length;){var e=zya(a,c);
if(e==C6){4==b&&(a.Lh=4,D6(15),d=!1);break}else if(e==Aya){a.Lh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Lh=1,D6(17),d=!1);a.Mf=a.Mf&&d;d||(F6(a),G6(a))},zya=function(a,b){var c=a.vn,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return Aya;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.vn=d+c;return e},Dya=function(a,b){a.jl=(0,g.C)();
B6(a);var c=b?window.location.hostname:"";a.oi=a.uh.clone();Y5(a.oi,"DOMAIN",c);Y5(a.oi,"t",a.G);try{a.Qf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Lh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in Cya)k=H6[l]=Cya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ad(g.dc("b/12014412"),d+"</body></html>");a.Qf.open();a.Qf.write(g.Wc(c));a.Qf.close();a.Qf.parentWindow.m=(0,g.x)(a.kN,a);a.Qf.parentWindow.d=(0,g.x)(a.BB,a,!0);a.Qf.parentWindow.rpcClose=(0,g.x)(a.BB,a,!1);c=a.Qf.createElement("DIV");a.Qf.parentWindow.document.body.appendChild(c);d=g.Dc(a.oi.toString());d=g.id(g.Ac(d));d=g.ad(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.bd(c,d);a.o.Gf(1)},B6=function(a){a.Qv=(0,g.C)()+a.C;
Eya(a,a.C)},Eya=function(a,b){if(null!=a.xl)throw Error("WatchDog timer not null");
a.xl=I6((0,g.x)(a.sN,a),b)},J6=function(a){a.xl&&(g.v.clearTimeout(a.xl),a.xl=null)},G6=function(a){a.o.uy()||a.Ji||a.o.Jo(a)},F6=function(a){J6(a);
g.Me(a.oq);a.oq=null;a.u.stop();g.Dsa(a.B);if(a.bd){var b=a.bd;a.bd=null;b.abort();b.dispose()}a.Qf&&(a.Qf=null)},E6=function(a,b){try{a.o.tB(a,b),a.o.Gf(4)}catch(c){}},Gya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Fya(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Gya(a,b,c,d,f)},f)})}},Fya=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Txa(d,a)},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Hya=function(a){this.o=a;
this.u=new x6},Iya=function(a){var b=L6(a.o,a.Kl,"/mail/images/cleardot.gif");
Z5(b);Gya(b.toString(),5E3,(0,g.x)(a.KE,a),3,2E3);a.Gf(1)},N6=function(a){var b=a.o.L;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.ke=new z6(a,void 0,void 0,void 0),a.ke.aj=a.Ps,b=a.o,b=L6(b,b.jn()?a.hm:null,a.Qs),D6(5),!g.ne||g.Sd(10))$5(b,"TYPE","xmlhttp"),A6(a.ke,b,!1,a.hm,!1);else{$5(b,"TYPE","html");var c=a.ke;a=!!a.hm;c.ql=3;c.uh=Z5(b.clone());Dya(c,a)}},O6=function(a){g.mf.call(this);
this.headers=new g.Pm;this.U=a||null;this.A=!1;this.T=this.o=null;this.fa=this.L="";this.F=0;this.B="";this.C=this.ba=this.H=this.Z=!1;this.G=0;this.M=null;this.ea="";this.R=this.aa=!1},Jya=function(a){return g.ne&&g.Rd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Kya=function(a){return"content-type"==a.toLowerCase()},Mya=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;Lya(a);P6(a)},Lya=function(a){a.Z||(a.Z=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Oya=function(a){if(a.A&&"undefined"!=typeof g.F1)if(a.T[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.H&&4==Q6(a))g.Zf(a.pB,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.sd(1,String(a.L));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Nya.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<Q6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";Lya(a)}}finally{P6(a)}}},P6=function(a,b){if(a.o){Pya(a);
var c=a.o,d=a.T[0]?g.Ja:null;a.o=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Pya=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.M&&(g.v.clearTimeout(a.M),a.M=null)},Q6=function(a){return a.o?a.o.readyState:0},S6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.fa+" "+a.L+" "+a.getStatus()+"]"},T6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new x6;this.H=a||null;this.L=null!=b?b:null;this.F=c||!1},Qya=function(a,b){this.o=a;
this.map=b;this.context=null},Rya=function(a){g.Oe.call(this,"statevent",a)},Sya=function(a,b){g.Oe.call(this,"timingevent",a);
this.size=b},Tya=function(a){g.Oe.call(this,"serverreachability",a)},Wya=function(a){Uya(a);
if(3==a.o){var b=a.Mm++,c=a.vo.clone();Y5(c,"SID",a.A);Y5(c,"RID",b);Y5(c,"TYPE","terminate");U6(a,c);b=new z6(a,a.A,b,void 0);b.ql=2;b.uh=Z5(c.clone());Txa(new Image,b.uh.toString());b.jl=(0,g.C)();B6(b)}Vya(a)},Xya=function(a){a.hF(1,0);
a.vo=L6(a,null,a.Os);V6(a)},Uya=function(a){a.yh&&(a.yh.abort(),a.yh=null);
a.yc&&(a.yc.cancel(),a.yc=null);a.Gg&&(g.v.clearTimeout(a.Gg),a.Gg=null);W6(a);a.ce&&(a.ce.cancel(),a.ce=null);a.Dh&&(g.v.clearTimeout(a.Dh),a.Dh=null)},Yya=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Qya(a.KJ++,b));2!=a.o&&3!=a.o||V6(a)},V6=function(a){a.ce||a.Dh||(a.Dh=I6((0,g.x)(a.AB,a),0),a.ek=0)},$ya=function(a,b){if(1==a.o){if(!b){a.Mm=Math.floor(1E5*Math.random());
var c=a.Mm++,d=new z6(a,"",c,void 0);d.aj=null;var e=X6(a),f=a.vo.clone();Y5(f,"RID",c);Y5(f,"CVER","1");U6(a,f);yya(d,f,e);a.ce=d;a.o=2}}else 3==a.o&&(b?Zya(a,b):0==a.u.length||a.ce||Zya(a))},Zya=function(a,b){if(b)if(6<a.Ki){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Mm-1;var d=X6(a)}else c=b.H,d=b.Aj;else c=a.Mm++,d=X6(a);var e=a.vo.clone();Y5(e,"SID",a.A);Y5(e,"RID",c);Y5(e,"AID",a.yk);U6(a,e);c=new z6(a,a.A,c,a.ek+1);c.aj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ce=c;yya(c,e,d)},U6=function(a,b){if(a.Md){var c=a.Md.Rx();
c&&g.Cb(c,function(d,e){Y5(b,e,d)})}},X6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Ki&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Ki?e:f-d;try{g.Cb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},aza=function(a){a.yc||a.Gg||(a.G=1,a.Gg=I6((0,g.x)(a.zB,a),0),a.Sj=0)},Y6=function(a){if(a.yc||a.Gg||3<=a.Sj)return!1;
a.G++;a.Gg=I6((0,g.x)(a.zB,a),bza(a,a.Sj));a.Sj++;return!0},M6=function(a,b,c){a.Uq=c;
a.ag=b.Vg;a.F||Xya(a)},W6=function(a){null!=a.Pi&&(g.v.clearTimeout(a.Pi),a.Pi=null)},bza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Z6=function(a,b){if(2==b||9==b){var c=null;
a.Md&&(c=null);var d=(0,g.x)(a.FO,a);c||(c=new g.Sm("//www.google.com/images/cleardot.gif"),Z5(c));Fya(c.toString(),1E4,d)}else D6(2);cza(a,b)},cza=function(a,b){a.o=0;
a.Md&&a.Md.ex(b);Vya(a);Uya(a)},Vya=function(a){a.o=0;
a.ag=-1;if(a.Md)if(0==a.B.length&&0==a.u.length)a.Md.Lr();else{g.pb(a.B);var b=g.pb(a.u);a.B.length=0;a.u.length=0;a.Md.Lr(b)}},L6=function(a,b,c){var d=g.$m(c);
if(""!=d.o)b&&g.Um(d,b+"."+d.o),g.Vm(d,d.B);else{var e=window.location;d=Xxa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Xl&&g.Cb(a.Xl,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.Ki);U6(a,d);return d},I6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){$6.dispatchEvent(new Rya($6,a))},dza=function(){},eza=function(){this.o=[];
this.u=[]},fza=function(a,b){this.action=a;
this.params=b||{}},a7=function(a,b){g.z.call(this);
this.o=new g.H(this.dN,0,this);g.A(this,this.o);this.Pd=5E3;this.u=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},b7=function(a,b,c){this.M=a;
this.F=b;this.A=new g.Wn;this.u=new a7(this.hO,this);this.o=null;this.Lb=!1;this.C=null;this.L="";this.H=this.B=0;this.G=[];this.R=c||!1},gza=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Uq,sessionId:a.o.A,arrayId:a.o.yk}},hza=function(a,b){a.H=b||0;
a.u.stop();a.o&&(3==a.o.o&&$ya(a.o),Wya(a.o));a.H=0},c7=function(a){return!!a.o&&3==a.o.o},iza=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},d7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.sd(4,a))||"";b&&(this.port=":"+b);this.domain=g.td(a)||"";a=g.Pc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.wc(a,"10.0")&&(this.u=!1))},e7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Dd(c+b,{})},f7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.B,d,!0),onError:g.Ra(a.A,e),Ce:g.Ra(a.C,e)};c&&(a.Ab=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uq(b,a)},mza=function(){var a=jza;
kza();g7.push(a);lza(g7)},h7=function(a,b){kza();
var c=g7,d=nza(a,String(b));g.gb(c)?oza(d):(lza(c),(0,g.y)(c,function(e){e(d)}))},kza=function(){g7||(g7=g.Ia("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",g7,void 0))},oza=function(a){var b=(i7+1)%50;
i7=b;j7[b]=a;k7||(k7=49==b)},lza=function(a){var b=j7;
if(b[0]){var c=i7,d=k7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
j7=Array(50);i7=-1;k7=!1}},nza=function(a,b){var c=((0,g.C)()-pza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},l7=function(a){g.N.call(this);
this.F=a;this.screens=[]},qza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},rza=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.Ae)(a.screens,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=qza(a,b[d])||c;return c},sza=function(a,b){var c=a.screens.length;
a.screens=(0,g.Ae)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},m7=function(a,b,c,d){g.N.call(this);
this.F=a;this.B=b;this.C=c;this.A=d;this.u=0;this.o=null;this.Ja=NaN},o7=function(a){l7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;n7(this);this.info("Initializing with "+h6(this.screens))},tza=function(a){if(a.screens.length){var b=(0,g.Jc)(a.screens,function(d){return d.id}),c=e7(a.u,"/pairing/get_lounge_token_batch");
f7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.VF,a),(0,g.x)(a.UF,a))}},n7=function(a){var b=cya(iya());
b=(0,g.Ae)(b,function(c){return!c.uuid});
return rza(a,b)},p7=function(a,b){kya((0,g.Jc)(a.screens,aya));
b&&jya()},r7=function(a,b){g.N.call(this);
this.F=b;var c=g.Ns("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;q7("Initialized with "+g.Ok(this.o))},uza=function(a,b,c){var d=e7(a.C,"/pairing/get_screen_availability");
f7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},s7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Jb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(q7("Updated online screens: "+g.Ok(a.o)),a.o=b,a.S("screenChange"));vza(a)},t7=function(a){isNaN(a.A)||g.Mo(a.A);
a.A=g.Ko((0,g.x)(a.Tu,a),0<a.B&&a.B<(0,g.C)()?2E4:1E4)},q7=function(a){h7("OnlineScreenService",a)},wza=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.lc("Requesting availability of screen w/o lounge token.")});
return b},vza=function(a){a=g.Jb(g.Db(a.o,function(b){return b}));
g.yb(a);a.length?g.Ms("yt-remote-online-screen-ids",a.join(","),60):g.Os("yt-remote-online-screen-ids")},u7=function(a){l7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};xza(this)},zza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.te();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=v7(a,k);uza(a.o,l,function(m){e(m?l:null)})}else c?yza(a,c,(0,g.x)(function(m){var n=v7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));uza(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},Aza=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},yza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Ab:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.uq(e7(a.C,"/pairing/get_lounge_token_batch"),e)},Bza=function(a){a.screens=a.u.te();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.screens))},xza=function(a){w7(a);
a.u=new o7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.dG,a));Bza(a);a.A=cya(g.Ns("yt-remote-automatic-screen-cache")||[]);w7(a);a.info("Initializing automatic screens: "+h6(a.A));a.o=new r7(a.C,(0,g.x)(a.te,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},v7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ms("yt-remote-automatic-screen-cache",(0,g.Jc)(a.A,aya)));w7(a);a.B[b.uuid]=b.id;g.Ms("yt-remote-device-id-map",a.B,31536E3);return b},w7=function(a){a.B=g.Ns("yt-remote-device-id-map")||{}},x7=function(a,b,c){g.N.call(this);
this.T=c;this.L=a;this.u=b;this.H=null},y7=function(a,b){h7(a.T,b)},z7=function(a,b){x7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.kP,this);this.B=(0,g.x)(this.AN,this);this.A=g.Ko((0,g.x)(function(){Cza(this,null)},this),12E4)},Dza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ok(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){y7(this,"Failed to send message: getMdxSessionStatus.")},a)):y7(a,"Sending yt message without session: "+g.Ok(b))},Cza=function(a,b){g.Mo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.fq,a),d=(0,g.x)(a.Be,a);a.my(b,c,d,5)}}else a.Be(Error("Waiting for session status timed out."))},A7=function(a,b,c){x7.call(this,a,b,"DialSession");
this.A=this.G=null;this.M="";this.U=c;this.B=null;this.F=g.Ja;this.C=NaN;this.R=(0,g.x)(this.nP,this);this.o=g.Ja},Eza=function(a){a.o=a.L.AD(a.M,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.fq(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.Be(b)},a))},Fza=function(a){var b={};
b.pairingCode=a.M;b.theme=a.U;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}mya()&&(b.env_useStageMdx=1);return g.Bd(b)},B7=function(a,b){x7.call(this,a,b,"ManualSession");
this.o=g.Ko((0,g.x)(this.zk,this,null),150)},C7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.rM,this)},Gza=function(a,b){return b?g.cb(a.A,function(c){return f6(b,c.label)},a):null},D7=function(a){h7("Controller",a)},jza=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},E7=function(a){return a.C||!!a.A.length||!!a.o},F7=function(a,b,c){b!=a.o&&(g.Me(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.yB,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.zk(null)):a.S("yt-remote-cast2-session-change",null))},Hza=function(a){var b=a.u.zD(),c=a.o&&a.o.u;
a=(0,g.Jc)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Gza(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Nza=function(a,b,c,d,e,f,k){Iza()?Jza(b,e,f,k)&&(H7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Kza(a,c):(window.__onGCastApiAvailable=function(l,m){l?Kza(a,c):(I7("Failed to load cast API: "+m),J7(!1),H7(!1),g.Os("yt-remote-cast-available"),g.Os("yt-remote-cast-receiver"),Lza(),c(!1))},d?g.Wo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?tya():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?s6():(sya(),r6(Mza.map(qya))))):G7("Cannot initialize because not running Chrome")},Lza=function(){G7("dispose");
var a=K7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Oza(!1);g.So(L7);L7.length=0},M7=function(){return!!g.Ns("yt-remote-cast-installed")},Pza=function(){var a=g.Ns("yt-remote-cast-receiver");
return a?a.friendlyName:null},Qza=function(){G7("clearCurrentReceiver");
g.Os("yt-remote-cast-receiver")},Rza=function(){return M7()?K7()?K7().getCastSession():(I7("getCastSelector: Cast is not initialized."),null):(I7("getCastSelector: Cast API is not installed!"),null)},O7=function(){M7()?K7()?N7()?(G7("Requesting cast selector."),K7().requestSession()):(G7("Wait for cast API to be ready to request the session."),L7.push(g.Ro("yt-remote-cast2-api-ready",O7))):I7("requestCastSelector: Cast is not initialized."):I7("requestCastSelector: Cast API is not installed!")},P7=
function(a,b){N7()?K7().setConnectedScreenStatus(a,b):I7("setConnectedScreenStatus called before ready.")},Iza=function(){var a=0<=g.Pc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Jt||a},Sza=function(a,b){K7().init(a,b)},Jza=function(a,b,c,d){var e=!1;
K7()||(a=new C7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ms("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){G7("onReceiverSelected: "+f.friendlyName);
g.Ms("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){G7("onReceiverResumed: "+f.friendlyName);
g.Ms("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){G7("onSessionChange: "+g6(f));
f||g.Os("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
G7("cloudview.createSingleton_: "+e);return e},K7=function(){return g.Ia("yt.mdx.remote.cloudview.instance_")},Kza=function(a,b){J7(!0);
H7(!1);Sza(a,function(c){c?(Oza(!0),g.To("yt-remote-cast2-api-ready")):(I7("Failed to initialize cast API."),J7(!1),g.Os("yt-remote-cast-available"),g.Os("yt-remote-cast-receiver"),Lza());b(c)})},G7=function(a){h7("cloudview",a)},I7=function(a){h7("cloudview",a)},J7=function(a){G7("setCastInstalled_ "+a);
g.Ms("yt-remote-cast-installed",a)},N7=function(){return!!g.Ia("yt.mdx.remote.cloudview.apiReady_")},Oza=function(a){G7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},H7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},Q7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.cg=!1;this.L=this.H=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},R7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.cg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.C)();a.C=0;a.u=0;a.H=0;a.L=0;a.B=NaN;a.A=!1},S7=function(a){return a.nb()?((0,g.C)()-a.F)/1E3:0},T7=function(a,b){a.G=b;
a.F=(0,g.C)()},U7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},V7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&R7(a)},W7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.o);b.hasPrevious=a.cg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.H;b.loadedTime=a.L;b.liveIngestionTime=a.B;return b},Y7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new eza;this.A=this.u=null;this.L=(0,g.x)(this.rK,this);this.G=(0,g.x)(this.Nm,this);this.H=(0,g.x)(this.qK,this);this.M=(0,g.x)(this.BK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Tv,this),Tza(this))):c=3;0!=c&&(b?this.Tv(c):g.Ko((0,g.x)(function(){this.Tv(c)},this),0));
var d=Rza();d&&X7(this,d);this.subscribe("yt-remote-cast2-session-change",this.M)},Z7=function(a){return new Q7(a.B.getPlayerContextData())},Tza=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ra(this.oM,b),this))},a)},Uza=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},$7=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},b8=function(a,b,c){var d=Z7(a);
T7(d,c);-1E3!=d.playerState&&(d.playerState=b);a8(a,d)},c8=function(a,b,c){a.B.sendMessage(b,c)},a8=function(a,b){Uza(a);
a.B.setPlayerContextData(W7(b));Tza(a)},X7=function(a,b){a.A&&(a.A.removeUpdateListener(a.L),a.A.removeMediaListener(a.G),a.Nm(null));
a.A=b;a.A&&(h7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.L),a.A.addMediaListener(a.G),a.A.media.length&&a.Nm(a.A.media[0]))},Vza=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=Z7(a);b.contentId!=d.videoId&&h7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;T7(d,a.u.getEstimatedTime());a8(a,d)}else h7("CP","No cast media video. Ignoring state update.")},d8=function(a,b,c){return(0,g.x)(function(d){this.lc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.lc("Retrying "+b+" using MDx browser channel."),c8(this,b,c))},a)},e8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.H=this.G=this.L=this.M=NaN;this.T=[];this.B=this.F=this.A=this.eb=this.o=null;this.Z=a;this.T.push(g.gp(window,"beforeunload",(0,g.x)(this.NF,this)));this.u=[];this.eb=new Q7;this.U=b.id;this.o=Wza(this,c);this.o.subscribe("handlerOpened",this.vK,this);this.o.subscribe("handlerClosed",this.sK,this);this.o.subscribe("handlerError",this.tK,this);this.o.subscribe("handlerMessage",this.uK,this);iza(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.eb.videoId;
g.Ps()&&g.Ms("yt-remote-session-video-id",d)},this)},f8=function(a){h7("conn",a)},Wza=function(a,b){return new b7(e7(a.Z,"/bc"),b)},g8=function(a,b){a.S("proxyStateChange",b)},Xza=function(a){a.C=g.Ko((0,g.x)(function(){f8("Connecting timeout");
this.ak(1)},a),2E4)},h8=function(a){g.Mo(a.C);
a.C=NaN},i8=function(a){g.Mo(a.M);
a.M=NaN},Yza=function(a){j8(a);
a.L=g.Ko((0,g.x)(function(){k8(this,"getNowPlaying")},a),2E4)},j8=function(a){g.Mo(a.L);
a.L=NaN},$za=function(a,b){b&&(h8(a),i8(a));
b==(c7(a.o)&&isNaN(a.C))?b&&(g8(a,1),k8(a,"getSubtitlesTrack")):b?(a.ky()&&a.eb.reset(),g8(a,1),k8(a,"getNowPlaying"),Zza(a)):a.ak(1)},aAa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.eb.videoId&&(g.Pb(b.params)?a.eb.o=null:a.eb.o=b.params,a.S("remotePlayerChange"))},bAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.eb.listId=b.params.listId||a.eb.listId;V7(a.eb,c,d);a.S("remoteQueueChange")},dAa=function(a,b){b.params=b.params||{};
bAa(a,b);cAa(a,b);a.S("autoplayDismissed")},cAa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
T7(a.eb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.eb.playerState&&(c=-1E3);a.eb.playerState=c;c=Number(b.params.loadedTime);a.eb.L=isNaN(c)?0:c;c=Number(b.params.duration);a.eb.H=isNaN(c)?0:c;c=a.eb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.eb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.eb.playerState?Yza(a):j8(a);a.S("remotePlayerChange")},eAa=function(a,b){if(-1E3!=
a.eb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.eb.playerState=c;c=parseInt(b.params.currentTime,10);T7(a.eb,isNaN(c)?0:c);a.S("remotePlayerChange")}},fAa=function(a,b){var c="true"==b.params.muted;
a.eb.volume=parseInt(b.params.volume,10);a.eb.muted=c;a.S("remotePlayerChange")},gAa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},hAa=function(a,b){var c="true"==b.params.hasNext;
a.eb.cg="true"==b.params.hasPrevious;a.eb.hasNext=c;a.S("previousNextChange")},Zza=function(a){g.Mo(a.H);
a.H=g.Ko((0,g.x)(a.ak,a,1),864E5)},k8=function(a,b,c){c?f8("Sending: action="+b+", params="+g.Ok(c)):f8("Sending: action="+b);
a.o.sendMessage(b,c)},l8=function(a){l7.call(this,"ScreenServiceProxy");
this.Od=a;this.o=[];this.o.push(this.Od.$_s("screenChange",(0,g.x)(this.iP,this)));this.o.push(this.Od.$_s("onlineScreenChange",(0,g.x)(this.SL,this)))},mAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;eya();o6();m8||(m8=new d7(b?b.loungeApiHost:void 0),mya()&&(m8.o="/api/loungedev"));n8||(n8=g.Ia("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",n8,void 0));iAa();var c=o8();if(!c){var d=new u7(m8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=o8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Nza(a,d,function(m){m?p8()&&P7(p8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.Ia("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),q8("Initializing: "+g.Ok(b)),r8.push(g.Ro("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),r8.push(g.Ro("yt-remote-cast2-receiver-selected",function(){s8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),r8.push(g.Ro("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),r8.push(g.Ro("yt-remote-cast2-session-change",jAa)),r8.push(g.Ro("yt-remote-connection-change",function(m){m?P7(p8(),"YouTube TV"):t8()||(P7(null,null),Qza())})),a=u8(),b.isAuto&&(a.id+="#dial"),g.Ao("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),q8(" -- with channel params: "+
g.Ok(a)),kAa(a),c.start(),p8()||lAa())},oAa=function(){var a=nAa();
M7()&&g.Ns("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},nAa=function(){var a=o8().Od.$_gos();
var b=v8();b&&w8()&&(j6(a,b)||a.push(b));return dya(a)},x8=function(){var a=pAa();
!a&&M7()&&Pza()&&(a={key:"cast-selector-receiver",name:Pza()});return a},pAa=function(){var a=nAa(),b=v8();
b||(b=t8());return g.cb(a,function(c){return b&&f6(b,c.key)?!0:!1})},v8=function(){var a=p8();
if(!a)return null;var b=o8().te();return k6(b,a)},jAa=function(a){q8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=v8();b&&b.id==a.id?P7(b.id,"YouTube TV"):(b&&y8(),z8(a,1))}else w8()&&y8()},y8=function(){N7()?K7().stopSession():I7("stopSession called before API ready.");
var a=w8();a&&(a.disconnect(1),A8(null))},B8=function(){var a=w8();
return!!a&&3!=a.getProxyState()},q8=function(a){h7("remote",a)},o8=function(){if(!C8){var a=g.Ia("yt.mdx.remote.screenService_");
C8=a?new l8(a):null}return C8},p8=function(){return g.Ia("yt.mdx.remote.currentScreenId_")},qAa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},rAa=function(){return g.Ia("yt.mdx.remote.connectData_")},s8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},w8=function(){return g.Ia("yt.mdx.remote.connection_")},A8=function(a){var b=w8();
s8(null);a||qAa("");g.Ga("yt.mdx.remote.connection_",a,void 0);n8&&((0,g.y)(n8,function(c){c(a)}),n8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},t8=function(){var a=g.Ps();
if(!a)return null;var b=o8();if(!b)return null;b=b.te();return k6(b,a)},z8=function(a,b){p8();
v8()&&v8();if(D8)E8=a;else{qAa(a.id);var c=new e8(m8,a,u8());c.connect(b,rAa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){w8()&&(w8(),A8(null))});
A8(c)}},lAa=function(){var a=t8();
a?(q8("Resume connection to: "+g6(a)),z8(a,0)):(p6(),Qza(),q8("Skipping connecting because no session screen found."))},iAa=function(){var a=u8();
if(g.Pb(a)){a=n6();var b=g.Ns("yt-remote-session-name")||"",c=g.Ns("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},u8=function(){return g.Ia("yt.mdx.remote.channelParams_")||{}},kAa=function(a){a?(g.Ms("yt-remote-session-app",a.app),g.Ms("yt-remote-session-name",a.name)):(g.Os("yt-remote-session-app"),g.Os("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.z.call(this);
var d=this;this.module=a;this.J=b;this.Xa=c;this.events=new g.Rr(this);this.L=this.events.N(this.J,"onVolumeChange",this.YA);this.B=!1;this.suggestion=null;this.C=new g.HC(64);this.o=new g.H(this.FC,500,this);this.u=new g.H(this.GC,1E3,this);this.G=new t6(this.MO,0,this);this.A={};this.H=new g.H(this.lD,1E3,this);this.F=new u6(this.seekTo,1E3,this);this.M=g.Ja;g.A(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.sL);this.events.N(b,"captionschanged",this.pK);this.events.N(b,"captionssettingschanged",
this.IC);this.events.N(b,"videoplayerreset",this.gq);this.events.N(b,"mdxautoplaycancel",function(){d.Xa.zx()});
a=this.Xa;a.ha();a.subscribe("proxyStateChange",this.sB,this);a.subscribe("remotePlayerChange",this.Rm,this);a.subscribe("remoteQueueChange",this.gq,this);a.subscribe("previousNextChange",this.oB,this);a.subscribe("nowAutoplaying",this.kB,this);a.subscribe("autoplayDismissed",this.HA,this);g.A(this,this.o);g.A(this,this.u);g.A(this,this.G);g.A(this,this.H);g.A(this,this.F);this.IC();this.gq();this.Rm()},sAa=function(a){a.Xb(0);
a.o.stop();G8(a,new g.HC(64))},I8=function(a,b){if(H8(a)&&!a.B){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Vb(c,b));a.Xa.xD(a.J.getVideoData(1).videoId,c);a.A=Z7(a.Xa).o}},J8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Xa.playVideo(c.videoId,b,d,e,c.playerParams,c.dg,Rxa(c));G8(a,new g.HC(1))},tAa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{My:1});
c&&c.length?(a.J.setOption("captions","track",b),a.B=!1):(a.J.loadModule("captions"),a.B=!0)}else a.J.setOption("captions","track",{})},H8=function(a){return Z7(a.Xa).videoId===a.J.getVideoData(1).videoId},G8=function(a,b){a.u.stop();
var c=a.C;if(!g.NC(c,b)){var d=g.T(b,2);d!==g.T(a.C,2)&&g.wT(a.J.app,d);a.C=b;uAa(a.module,c,b)}},K8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-manual-pairing-popup-title",W:"Connecting to your TV on web using a code will be going away soon"},{D:"div",I:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],W:"Learn more"},{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],W:"OK"}]}]}]});this.o=new g.NN(this,250);this.learnMoreButton=
this.da("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.da("ytp-mdx-manual-pairing-popup-ok");g.A(this,this.o);this.N(this.learnMoreButton,"click",this.u);this.N(this.okButton,"click",this.A)},L8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.o=new g.NN(this,250);this.cancelButton=this.da("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.da("ytp-mdx-privacy-popup-confirm");g.A(this,this.o);this.N(this.cancelButton,"click",this.u);this.N(this.confirmButton,"click",this.A)},M8=function(a){g.V.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.gN()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.api=a;this.o=new g.NN(this,250);g.A(this,this.o);this.N(a,"presentingplayerstatechange",this.u);vAa(this,g.rL(a))},vAa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.IM("Error on $RECEIVER_NAME",c):b.nb()||g.T(b,4)?g.IM("Playing on $RECEIVER_NAME",c):g.IM("Connected to $RECEIVER_NAME",c);a.na("statustext",c);a.o.show()}else a.o.hide()},N8=function(a,b){g.CP.call(this,"Play on",0,a,b);
this.J=a;this.ni={};this.N(a,"onMdxReceiversChange",this.B);this.N(a,"presentingplayerstatechange",this.B);this.B()},O8=function(a){g.XL.call(this,a);
this.Bf={key:i6(),name:"This computer"};this.pe=null;this.subscriptions=[];this.Fu=this.Xa=null;this.ni=[this.Bf];this.Ah=this.Bf;this.Pb=new g.HC(64);this.dz=0;this.ld=-1;this.Bk=null;this.Sm=this.lp=!1;this.zj=this.bl=null;if(!g.$y(this.player.O())){a=this.player;var b=g.eC(a);b&&(b=b.Gm())&&(b=new N8(a,b),g.A(this,b));b=new M8(a);g.A(this,b);g.LL(a,b.element,4);this.bl=new L8;g.A(this,this.bl);g.LL(a,this.bl.element,4);g.O(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.Bk=new K8,g.A(this,this.Bk),g.LL(a,this.Bk.element,4));this.Sm=!!t8();this.lp=!!g.Ns("yt-remote-manual-pairing-warning-shown")}},P8=function(a){a.zj&&(a.player.removeEventListener("presentingplayerstatechange",a.zj),a.zj=null)},uAa=function(a,b,c){a.Pb=c;
a.player.S("presentingplayerstatechange",new g.sH(c,b))},wAa=function(a,b,c){var d=!1;
1===b?d=!a.Sm:2===b&&(d=!a.lp);d&&g.uH(c,8)&&(a.player.pauseVideo(),P8(a))},Q8=function(a,b){if(b.key!==a.Ah.key)if(b.key===a.Bf.key)y8();
else{if(a.Bk&&!a.lp&&b!==a.Bf&&"cast-selector-receiver"!==b.key&&g.iz(a.player.O()))xAa(a);else{var c;(c=!g.O(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Sm||!a.bl);(c?0:g.iz(a.player.O())||g.mz(a.player.O()))&&yAa(a)}a.Ah=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.O(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Da(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.dg,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Rxa(c))&&(d.locationInfo=c);c=d}q8("Connecting to: "+g.Ok(b));"cast-selector-receiver"==b.key?(s8(c||null),c=
c||null,N7()?K7().setLaunchParams(c):I7("setLaunchParams called before ready.")):!c&&B8()&&p8()==b.key?c6("yt-remote-connection-change",!0):(y8(),s8(c||null),c=o8().te(),(c=k6(c,b.key))&&z8(c,1))}},yAa=function(a){g.rL(a.player).nb()?a.player.pauseVideo():(a.zj=function(b){wAa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.zj));
a.bl&&a.bl.dc();w8()||(D8=!0)},xAa=function(a){g.rL(a.player).nb()?a.player.pauseVideo():(a.zj=function(b){wAa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.zj));
a.Bk&&a.Bk.dc();w8()||(D8=!0)},Cya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},H6={"'":"\\'"},zAa={},$xa={SP:"atp",fT:"ska",OS:"que",cS:"mus",eT:"sus",cR:"dsp",WS:"seq"},q6,m6="",rya=nya("loadCastFramework")||nya("loadCastApplicationFramework"),Mza=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(t6,g.z);g.h=t6.prototype;g.h.KF=function(a){this.B=arguments;this.o=!1;this.Ja?this.A=(0,g.C)()+this.Pd:this.Ja=g.Zf(this.C,this.Pd)};
g.h.stop=function(){this.Ja&&(g.v.clearTimeout(this.Ja),this.Ja=null);this.A=null;this.o=!1;this.B=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.h.X=function(){this.stop();t6.sc.X.call(this)};
g.h.LF=function(){this.A?(this.Ja=g.Zf(this.C,this.A-(0,g.C)()),this.A=null):(this.Ja=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.r(u6,g.z);g.h=u6.prototype;g.h.qz=function(a){this.A=arguments;this.Ja||this.u?this.o=!0:v6(this)};
g.h.stop=function(){this.Ja&&(g.v.clearTimeout(this.Ja),this.Ja=null,this.o=!1,this.A=null)};
g.h.pause=function(){this.u++};
g.h.resume=function(){this.u--;this.u||!this.o||this.Ja||(this.o=!1,v6(this))};
g.h.X=function(){g.z.prototype.X.call(this);this.stop()};x6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
x6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};y6.prototype.o=null;y6.prototype.getOptions=function(){var a;(a=this.o)||(a={},vya(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var R8;g.Ta(uya,y6);R8=new uya;g.h=z6.prototype;g.h.aj=null;g.h.Mf=!1;g.h.xl=null;g.h.Qv=null;g.h.jl=null;g.h.ql=null;g.h.uh=null;g.h.oi=null;g.h.Aj=null;g.h.bd=null;g.h.vn=0;g.h.Qf=null;g.h.Wq=null;g.h.Lh=null;g.h.im=-1;g.h.uC=!0;g.h.Ji=!1;g.h.Rs=0;g.h.oq=null;var Aya={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.UN=function(a){a=a.target;var b=this.oq;b&&3==Q6(a)?b.qz():this.uD(a)};
g.h.uD=function(a){try{if(a==this.bd)a:{var b=Q6(this.bd),c=this.bd.F,d=this.bd.getStatus();if(g.ne&&!g.Sd(10)||g.pe&&!g.Rd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Bh&&!S6(this.bd))break a;this.Ji||4!=b||7==c||(8==c||0>=d?this.o.Gf(3):this.o.Gf(2));J6(this);var e=this.bd.getStatus();this.im=e;var f=S6(this.bd);(this.Mf=200==e)?(4==b&&F6(this),this.F?(Bya(this,b,f),g.Bh&&this.Mf&&3==b&&(this.B.oa(this.u,"tick",this.NN),this.u.start())):E6(this,f),this.Mf&&!this.Ji&&(4==b?this.o.Jo(this):(this.Mf=
!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Lh=3,D6(13)):(this.Lh=0,D6(14)),F6(this),G6(this))}}catch(k){this.bd&&S6(this.bd)}finally{}};
g.h.NN=function(){var a=Q6(this.bd),b=S6(this.bd);this.vn<b.length&&(J6(this),Bya(this,a,b),this.Mf&&4!=a&&B6(this))};
g.h.kN=function(a){I6((0,g.x)(this.jN,this,a),0)};
g.h.jN=function(a){this.Ji||(J6(this),E6(this,a),B6(this))};
g.h.BB=function(a){I6((0,g.x)(this.iN,this,a),0)};
g.h.iN=function(a){this.Ji||(F6(this),this.Mf=a,this.o.Jo(this),this.o.Gf(4))};
g.h.cancel=function(){this.Ji=!0;F6(this)};
g.h.sN=function(){this.xl=null;var a=(0,g.C)();0<=a-this.Qv?(2!=this.ql&&this.o.Gf(3),F6(this),this.Lh=2,D6(18),G6(this)):Eya(this,this.Qv-a)};
g.h.getLastError=function(){return this.Lh};g.h=Hya.prototype;g.h.Ps=null;g.h.ke=null;g.h.qq=!1;g.h.vy=null;g.h.ro=null;g.h.Bt=null;g.h.Qs=null;g.h.Oe=null;g.h.Vg=-1;g.h.hm=null;g.h.Kl=null;g.h.connect=function(a){this.Qs=a;a=L6(this.o,null,this.Qs);D6(3);this.vy=(0,g.C)();var b=this.o.H;null!=b?(this.hm=b[0],(this.Kl=b[1])?(this.Oe=1,Iya(this)):(this.Oe=2,N6(this))):($5(a,"MODE","init"),this.ke=new z6(this,void 0,void 0,void 0),this.ke.aj=this.Ps,A6(this.ke,a,!1,null,!0),this.Oe=0)};
g.h.KE=function(a){if(a)this.Oe=2,N6(this);else{D6(4);var b=this.o;b.ag=b.yh.Vg;Z6(b,9)}a&&this.Gf(2)};
g.h.Ur=function(a){return this.o.Ur(a)};
g.h.abort=function(){this.ke&&(this.ke.cancel(),this.ke=null);this.Vg=-1};
g.h.uy=function(){return!1};
g.h.tB=function(a,b){this.Vg=a.im;if(0==this.Oe)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.ag=this.Vg;Z6(c,2);return}this.hm=c[0];this.Kl=c[1]}else c=this.o,c.ag=this.Vg,Z6(c,2);else if(2==this.Oe)if(this.qq)D6(7),this.Bt=(0,g.C)();else if("11111"==b){if(D6(6),this.qq=!0,this.ro=(0,g.C)(),c=this.ro-this.vy,!g.ne||g.Sd(10)||500>c)this.Vg=200,this.ke.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.ro=this.Bt=(0,g.C)(),this.qq=!1};
g.h.Jo=function(){this.Vg=this.ke.im;if(this.ke.Mf)0==this.Oe?this.Kl?(this.Oe=1,Iya(this)):(this.Oe=2,N6(this)):2==this.Oe&&((!g.ne||g.Sd(10)?!this.qq:200>this.Bt-this.ro)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Oe?D6(9):2==this.Oe&&D6(10);var a=this.o;this.ke.getLastError();a.ag=this.Vg;Z6(a,2)}};
g.h.jn=function(){return this.o.jn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Gf=function(a){this.o.Gf(a)};g.Ta(O6,g.mf);var Nya=/^https?$/i,AAa=["POST","PUT"];g.h=O6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.L+"; newUri="+a);b=b?b.toUpperCase():"GET";this.L=a;this.B="";this.F=0;this.fa=b;this.Z=!1;this.A=!0;this.o=this.U?wya(this.U):wya(R8);this.T=this.U?this.U.getOptions():R8.getOptions();this.o.onreadystatechange=(0,g.x)(this.pB,this);try{b6(R6(this,"Opening Xhr")),this.ba=!0,this.o.open(b,String(a),!0),this.ba=!1}catch(f){b6(R6(this,"Error opening Xhr: "+f.message));Mya(this,f);return}a=
c||"";var e=this.headers.clone();d&&Wxa(d,function(f,k){e.set(k,f)});
d=g.cb(e.Me(),Kya);c=g.v.FormData&&a instanceof g.v.FormData;!g.fb(AAa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{Pya(this),0<this.G&&(this.R=Jya(this.o),b6(R6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.wy,this)):this.M=g.Zf(this.wy,this.G,this)),b6(R6(this,"Sending request")),this.H=!0,this.o.send(a),this.H=!1}catch(f){b6(R6(this,"Send error: "+f.message)),Mya(this,f)}};
g.h.wy=function(){"undefined"!=typeof g.F1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,R6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.A&&(R6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.h.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),P6(this,!0));O6.sc.X.call(this)};
g.h.pB=function(){this.ha()||(this.ba||this.H||this.C?Oya(this):this.qM())};
g.h.qM=function(){Oya(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<Q6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.h=T6.prototype;g.h.Xl=null;g.h.ce=null;g.h.yc=null;g.h.Os=null;g.h.vo=null;g.h.Rw=null;g.h.Io=null;g.h.Mm=0;g.h.KJ=0;g.h.Md=null;g.h.Dh=null;g.h.Gg=null;g.h.Pi=null;g.h.yh=null;g.h.Uq=null;g.h.yk=-1;g.h.cz=-1;g.h.ag=-1;g.h.ek=0;g.h.Sj=0;g.h.Ki=8;var $6=new g.mf;g.Ta(Rya,g.Oe);g.Ta(Sya,g.Oe);g.Ta(Tya,g.Oe);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Os=b;this.Xl=c||{};d&&void 0!==e&&(this.Xl.OSID=d,this.Xl.OAID=e);this.F?(I6((0,g.x)(this.kx,this,a),100),Xya(this)):this.kx(a)};
g.h.kx=function(a){this.yh=new Hya(this);this.yh.Ps=null;this.yh.u=this.C;this.yh.connect(a)};
g.h.uy=function(){return 0==this.o};
g.h.AB=function(a){this.Dh=null;$ya(this,a)};
g.h.zB=function(){this.Gg=null;this.yc=new z6(this,this.A,"rpc",this.G);this.yc.aj=null;this.yc.Rs=0;var a=this.Rw.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.A);Y5(a,"CI",this.Uq?"0":"1");Y5(a,"AID",this.yk);U6(this,a);if(!g.ne||g.Sd(10))Y5(a,"TYPE","xmlhttp"),A6(this.yc,a,!0,this.Io,!1);else{Y5(a,"TYPE","html");var b=this.yc,c=!!this.Io;b.ql=3;b.uh=Z5(a.clone());Dya(b,c)}};
g.h.tB=function(a,b){if(0!=this.o&&(this.yc==a||this.ce==a))if(this.ag=a.im,this.ce==a&&3==this.o)if(7<this.Ki){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Gg){if(this.yc)if(this.yc.jl+3E3<this.ce.jl)W6(this),this.yc.cancel(),this.yc=null;else break a;Y6(this);D6(19)}}else this.cz=c[1],0<this.cz-this.yk&&37500>c[2]&&this.Uq&&0==this.Sj&&!this.Pi&&(this.Pi=I6((0,g.x)(this.lK,this),6E3));else Z6(this,11)}else b!=zAa.uQ.o&&Z6(this,11);else if(this.yc==
a&&W6(this),!g.lc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.yk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Io=e[2],e=e[3],null!=e?this.Ki=e:this.Ki=6,this.o=3,this.Md&&this.Md.gx(),this.Rw=L6(this,this.jn()?this.Io:null,this.Os),aza(this)):"stop"==e[0]&&Z6(this,7):3==this.o&&("stop"==e[0]?Z6(this,7):"noop"!=e[0]&&this.Md&&this.Md.fx(e),this.Sj=0)}}};
g.h.lK=function(){null!=this.Pi&&(this.Pi=null,this.yc.cancel(),this.yc=null,Y6(this),D6(20))};
g.h.Jo=function(a){if(this.yc==a){W6(this);this.yc=null;var b=2}else if(this.ce==a)this.ce=null,b=1;else return;this.ag=a.im;if(0!=this.o)if(a.Mf)1==b?(b=(0,g.C)()-a.jl,$6.dispatchEvent(new Sya($6,a.Aj?a.Aj.length:0,b,this.ek)),V6(this),this.B.length=0):aza(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ag)){if(d=1==b)this.ce||this.Dh||1==this.o||2<=this.ek?d=!1:(this.Dh=I6((0,g.x)(this.AB,this,a),bza(this,this.ek)),this.ek++,d=!0);d=!(d||2==b&&Y6(this))}if(d)switch(c){case 1:Z6(this,
5);break;case 4:Z6(this,10);break;case 3:Z6(this,6);break;case 7:Z6(this,12);break;default:Z6(this,2)}}};
g.h.hF=function(a){if(!g.fb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.FO=function(a){a?D6(2):(D6(1),cza(this,8))};
g.h.Ur=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.aa=!1;return a};
g.h.isActive=function(){return!!this.Md&&this.Md.isActive(this)};
g.h.Gf=function(a){$6.dispatchEvent(new Tya($6,a))};
g.h.jn=function(){return!(!g.ne||g.Sd(10))};
g.h=dza.prototype;g.h.gx=function(){};
g.h.fx=function(){};
g.h.ex=function(){};
g.h.Lr=function(){};
g.h.Rx=function(){return{}};
g.h.isActive=function(){return!0};g.h=eza.prototype;g.h.isEmpty=function(){return g.gb(this.o)&&g.gb(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.fb(this.o,a)||g.fb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Isa)(b,a);0<=c?(g.kb(b,c),b=!0):b=!1;return b||g.lb(this.u,a)};
g.h.Yd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(a7,g.z);g.h=a7.prototype;g.h.dN=function(){this.Pd=Math.min(3E5,2*this.Pd);this.A();this.u&&this.start()};
g.h.start=function(){var a=this.Pd+15E3*Math.random();this.o.bb(a);this.u=(0,g.C)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Pd=5E3};g.Ta(b7,dza);g.h=b7.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.hi=function(a){return this.A.bj(a)};
g.h.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.h.dispose=function(){this.Lb||(this.Lb=!0,g.Me(this.A),hza(this),g.Me(this.u),this.u=null)};
g.h.ha=function(){return this.Lb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.L="";this.u.stop();this.C=a||null;this.B=b||0;a=this.M+"/test";b=this.M+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Md=null);d.Md=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.yk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Vb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):c7(this)&&Yya(this.o,c)};
g.h.gx=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)Yya(this.o,a[b])}this.S("handlerOpened")};
g.h.ex=function(a){var b=2==a&&401==this.o.ag;4==a||b||this.u.start();this.S("handlerError",a)};
g.h.Lr=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.Rx=function(){var a={v:2};this.L&&(a.gsessionid=this.L);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.C&&g.Vb(a,this.C);return a};
g.h.fx=function(a){"S"==a[0]?this.L=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Wya(this.o)):this.S("handlerMessage",new fza(a[0],a[1]))};
g.h.hO=function(){this.u.isActive();var a=this.o,b=0;a.yc&&b++;a.ce&&b++;0==b&&this.connect(this.C,this.B)};d7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
d7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
d7.prototype.C=function(a){a(Error("request timed out"))};var pza=(0,g.C)(),g7=null,j7=Array(50),i7=-1,k7=!1;g.Ta(l7,g.N);l7.prototype.te=function(){return this.screens};
l7.prototype.contains=function(a){return!!j6(this.screens,a)};
l7.prototype.get=function(a){return a?k6(this.screens,a):null};
l7.prototype.info=function(a){h7(this.F,a)};g.r(m7,g.N);g.h=m7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ja)&&this.yD()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ja)||(g.Mo(this.Ja),this.Ja=NaN)};
g.h.X=function(){this.stop();g.N.prototype.X.call(this)};
g.h.yD=function(){this.Ja=NaN;this.o=g.uq(e7(this.F,"/pairing/get_screen"),{method:"POST",Ab:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.gP,this),onError:(0,g.x)(this.fP,this),Ce:(0,g.x)(this.hP,this)})};
g.h.gP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.A;this.S("pairingComplete",new e6(c))};
g.h.fP=function(a){this.o=null;a.status&&404==a.status?this.u>=BAa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=BAa[this.u],this.Ja=g.Ko((0,g.x)(this.yD,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.h.hP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var BAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(o7,l7);g.h=o7.prototype;g.h.start=function(){n7(this)&&this.S("screenChange");!g.Ns("yt-remote-lounge-token-expiration")&&tza(this);g.Mo(this.o);this.o=g.Ko((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){n7(this);qza(this,a);p7(this,!1);this.S("screenChange");b(a);a.token||tza(this)};
g.h.remove=function(a,b){var c=n7(this);sza(this,a)&&(p7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.h.Sq=function(a,b,c,d){var e=n7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,p7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.h.X=function(){g.Mo(this.o);o7.sc.X.call(this)};
g.h.VF=function(a){n7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}p7(this,!b);b&&h7(this.F,"Missed "+b+" lounge tokens.")};
g.h.UF=function(a){h7(this.F,"Requesting lounge tokens failed: "+a)};g.r(r7,g.N);g.h=r7.prototype;g.h.start=function(){var a=parseInt(g.Ns("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.C)()-144E5<a?0:a)?t7(this):(this.B=(0,g.C)()+3E5,g.Ms("yt-remote-fast-check-period",this.B),this.Tu())};
g.h.isEmpty=function(){return g.Pb(this.o)};
g.h.update=function(){q7("Updating availability on schedule.");var a=this.F(),b=g.Db(this.o,function(c,d){return c&&!!k6(a,d)},this);
s7(this,b)};
g.h.X=function(){g.Mo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.h.Tu=function(){g.Mo(this.A);this.A=NaN;this.u&&this.u.abort();var a=wza(this);if(a6(a)){var b=e7(this.C,"/pairing/get_screen_availability");this.u=f7(this.C,b,{lounge_token:g.Jb(a).join(",")},(0,g.x)(this.MM,this,a),(0,g.x)(this.LM,this))}else s7(this,{}),t7(this)};
g.h.MM=function(a,b){this.u=null;var c=g.Jb(wza(this));if(g.zb(c,g.Jb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;s7(this,d);t7(this)}else this.lc("Changing Screen set during request."),this.Tu()};
g.h.LM=function(a){this.lc("Screen availability failed: "+a);this.u=null;t7(this)};
g.h.lc=function(a){h7("OnlineScreenService",a)};g.Ta(u7,l7);g.h=u7.prototype;g.h.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.h.add=function(a,b,c){this.u.add(a,b,c)};
g.h.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.h.Sq=function(a,b,c,d){this.u.contains(a)?this.u.Sq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,h7(this.F,a),d(Error(a)))};
g.h.te=function(a){return a?this.screens:g.ob(this.screens,(0,g.Ae)(this.A,function(b){return!this.contains(b)},this))};
g.h.zD=function(){return(0,g.Ae)(this.te(!0),function(a){return!!this.o.o[a.id]},this)};
g.h.AD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new m7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Me(f);d(v7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Me(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.jP=function(a,b,c,d){g.uq(e7(this.C,"/pairing/get_screen"),{method:"POST",Ab:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||Aza(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Aza(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(v7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Ce:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.Me(this.u);g.Me(this.o);u7.sc.X.call(this)};
g.h.dG=function(){Bza(this);this.S("screenChange");this.o.update()};
u7.prototype.dispose=u7.prototype.dispose;g.Ta(x7,g.N);g.h=x7.prototype;g.h.getScreen=function(){return this.H};
g.h.fq=function(a){this.H=a;this.S("sessionScreen",this.H)};
g.h.Be=function(a){this.ha()||(a&&y7(this,""+a),this.H=null,this.S("sessionScreen",null))};
g.h.info=function(a){h7(this.T,a)};
g.h.CD=function(){return null};
g.h.ev=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){y7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.ev("");x7.sc.X.call(this)};g.r(z7,x7);g.h=z7.prototype;g.h.dv=function(a){if(this.o){if(this.o==a)return;y7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Dza(this)};
g.h.zk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ok(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Be()},this),(0,g.x)(function(){this.Be(Error("Failed to stop receiver app."))},this)):this.Be(Error("Stopping cast device witout session."))};
g.h.ev=function(){};
g.h.X=function(){this.info("disposeInternal");g.Mo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;x7.prototype.X.call(this)};
g.h.AN=function(a,b){if(!this.ha())if(b){var c=w6(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ok(c));switch(d){case "mdxSessionStatus":Cza(this,c.screenId);break;default:y7(this,"Unknown youtube message: "+d)}}else y7(this,"Unable to parse message.")}else y7(this,"No data in message.")};
g.h.my=function(a,b,c,d){zza(this.L,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(y7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ko((0,g.x)(this.my,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.CD=function(){return this.o};
g.h.kP=function(a){this.ha()||a||(y7(this,"Cast session died."),this.Be())};g.r(A7,x7);g.h=A7.prototype;g.h.dv=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.h.zk=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ja;g.Mo(this.C);this.A?this.A.stop((0,g.x)(this.Be,this,null),(0,g.x)(this.Be,this,"Failed to stop DIAL device.")):this.Be()};
g.h.X=function(){this.o();this.o=g.Ja;g.Mo(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;x7.prototype.X.call(this)};
g.h.nP=function(a){this.ha()||a||(y7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.Be())};
g.h.gt=function(a){this.M=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Fza(this));a(b);Eza(this)}else this.F=(0,g.x)(function(){g.Mo(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Fza(this));a(c);Eza(this)},this),this.C=g.Ko((0,g.x)(function(){this.F()},this),100)};
g.h.xG=function(a,b,c){zza(this.L,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.fq(d),b(new chrome.cast.DialLaunchResponse(!1))):this.gt(b,c)},this),(0,g.x)(function(d){y7(this,"Failed to get DIAL screen: "+d);
this.gt(b,c)},this))};g.r(B7,x7);B7.prototype.stop=function(){this.Be()};
B7.prototype.dv=function(){};
B7.prototype.zk=function(){g.Mo(this.o);this.o=NaN;var a=k6(this.L.te(),this.u.label);a?this.fq(a):this.Be(Error("No such screen"))};
B7.prototype.X=function(){g.Mo(this.o);this.o=NaN;x7.prototype.X.call(this)};g.r(C7,g.N);g.h=C7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.vM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.wB,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.IK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),mza(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.BD,this)),this.A=Hza(this),chrome.cast.setCustomReceivers(this.A,g.Ja,(0,g.x)(function(k){this.lc("Failed to set initial custom receivers: "+g.Ok(k))},this)),this.S("yt-remote-cast2-availability-change",E7(this)),b(!0))},this),(0,g.x)(function(k){this.lc("Failed to initialize API: "+g.Ok(k));
b(!1)},this))};
g.h.pO=function(a,b){D7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)D7("Unsetting old screen status: "+this.o.u.friendlyName),F7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.te(),a);if(!c){D7("setConnectedScreenStatus: Unknown screen.");return}var d=Gza(this,c);d||(D7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ja,(0,g.x)(function(e){this.lc("Failed to set initial custom receivers: "+g.Ok(e))},this)));
D7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);F7(this,new B7(this.u,d),!0)}this.o.ev(b)}else D7("setConnectedScreenStatus: no screen.")};
g.h.qO=function(a){this.ha()?this.lc("Setting connection data on disposed cast v2"):this.o?this.o.zk(a):this.lc("Setting connection data without a session")};
g.h.mP=function(){this.ha()?this.lc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),F7(this,null)):D7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.wB,this),(0,g.x)(this.QM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.BD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=jza,b=g.Ia("yt.mdx.remote.debug.handlers_");g.lb(b||[],a);g.Me(this.o);g.N.prototype.X.call(this)};
g.h.lc=function(a){h7("Controller",a)};
g.h.yB=function(a,b){this.o==a&&(b||F7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.h.rM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),D7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)D7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{D7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:F7(this,
new B7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:F7(this,new A7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:F7(this,new z7(this.u,a));break;default:this.lc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.lc("Stopping receiver w/o session: "+a.friendlyName)}else this.lc("onReceiverAction_ called without receiver.")};
g.h.IK=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.lc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.lc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return D7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.lc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);F7(this,new A7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.xG,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.gt,b))};
g.h.wB=function(a){if(!this.ha()){D7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)D7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),F7(this,new z7(this.u,b),!0);else{this.lc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.te(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(D7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Me(this.o),this.o=new z7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.yB,this,this.o)),this.o.zk(null));this.o.dv(a)}}};
g.h.lP=function(){return this.o?this.o.CD():null};
g.h.QM=function(a){this.ha()||(this.lc("Failed to estabilish a session: "+g.Ok(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&F7(this,null))};
g.h.vM=function(a){D7("Receiver availability updated: "+a);if(!this.ha()){var b=E7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;E7(this)!=b&&this.S("yt-remote-cast2-availability-change",E7(this))}};
g.h.BD=function(){this.ha()||(this.A=Hza(this),D7("Updating custom receivers: "+g.Ok(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ja,(0,g.x)(function(){this.lc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",E7(this)))};
C7.prototype.setLaunchParams=C7.prototype.qO;C7.prototype.setConnectedScreenStatus=C7.prototype.pO;C7.prototype.stopSession=C7.prototype.mP;C7.prototype.getCastSession=C7.prototype.lP;C7.prototype.requestSession=C7.prototype.requestSession;C7.prototype.init=C7.prototype.init;C7.prototype.dispose=C7.prototype.dispose;var L7=[];g.h=Q7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";R7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.cg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.H=a.duration,this.L=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.h.nb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.A?this.H+S7(this):this.H};
g.h.clone=function(){return new Q7(W7(this))};g.r(Y7,g.N);g.h=Y7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,d8(this,"play")):c8(this,"play"),b8(this,1,U7(Z7(this))),this.S("remotePlayerChange")):$7(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,d8(this,"pause")):c8(this,"pause"),b8(this,2,U7(Z7(this))),this.S("remotePlayerChange")):$7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=Z7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.nb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,d8(this,"seekTo",{newTime:a}))}else c8(this,"seekTo",{newTime:a});b8(this,3,a);this.S("remotePlayerChange")}else $7(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,d8(this,"stopVideo")):c8(this,"stopVideo");var a=Z7(this);a.index=-1;a.videoId="";R7(a);a8(this,a);this.S("remotePlayerChange")}else $7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=Z7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){h7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.lc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){h7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.lc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);c8(this,"setVolume",e)}c.muted=b;c.volume=a;a8(this,c)}else $7(this,g.Ra(this.setVolume,a,b))};
g.h.xD=function(a,b){if(1==this.o){var c=Z7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ok(b.style),g.Vb(d,c.o));c8(this,"setSubtitlesTrack",d);a8(this,c)}else $7(this,g.Ra(this.xD,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();c8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=Z7(this);d.audioTrackId=c;a8(this,d)}else $7(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=Z7(this);c=c||0;var m={videoId:a,currentIndex:c};V7(l,a,c);void 0!==b&&(T7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Ok(k));c8(this,"setPlaylist",m);d||a8(this,l)};
g.h.lq=function(a,b){if(1==this.o){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"previous")}else $7(this,g.Ra(this.lq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"next")}else $7(this,g.Ra(this.nextVideo,a,b))};
g.h.zx=function(){1==this.o?c8(this,"dismissAutoplay"):$7(this,this.zx)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.h.X=function(){Uza(this);this.B=null;this.C.clear();X7(this,null);g.N.prototype.X.call(this)};
g.h.Tv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.gb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.oM=function(a,b){this.S(a,b)};
g.h.rK=function(a){if(!a)this.Nm(null),X7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=Z7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)h7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,a8(this,b)}};
g.h.Nm=function(a){h7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.H);if(this.u=a)this.u.addUpdateListener(this.H),Vza(this),this.S("remotePlayerChange")};
g.h.qK=function(a){a?(Vza(this),this.S("remotePlayerChange")):this.Nm(null)};
g.h.Av=function(){c8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.BK=function(){var a=Rza();a&&X7(this,a)};
g.h.lc=function(a){h7("CP",a)};g.r(e8,g.N);g.h=e8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.eb.listId=c);this.eb.videoId=d;this.eb.index=k||0;this.eb.state=3;T7(this.eb,m);this.B="UNSUPPORTED";f8("Connecting with setPlaylist and params: "+g.Ok(l));this.o.connect({method:"setPlaylist",
params:g.Ok(l)},a,hya())}else f8("Connecting without params"),this.o.connect({},a,hya());Xza(this)};
g.h.dispose=function(){this.ha()||(this.S("beforeDispose"),g8(this,3));g.N.prototype.dispose.call(this)};
g.h.X=function(){h8(this);j8(this);i8(this);g.Mo(this.G);this.G=NaN;g.Mo(this.H);this.H=NaN;this.A=null;g.hp(this.T);this.T.length=0;this.o.dispose();g.N.prototype.X.call(this);this.B=this.F=this.u=this.eb=this.o=null};
g.h.NF=function(){this.ak(2)};
g.h.vK=function(){f8("Channel opened");this.R&&(this.R=!1,i8(this),this.M=g.Ko((0,g.x)(function(){f8("Timing out waiting for a screen.");this.ak(1)},this),15E3));
lya(gza(this.o),this.U)};
g.h.sK=function(){f8("Channel closed");isNaN(this.C)?p6(!0):p6();this.dispose()};
g.h.tK=function(a){p6();isNaN(this.dm())?(f8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,f8("Channel error: "+a+" with reconnection in "+this.dm()+" ms"),g8(this,2))};
g.h.uK=function(a){a.params?f8("Received: action="+a.action+", params="+g.Ok(a.params)):f8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=w6(a.params.devices);this.u=(0,g.Jc)(a,function(c){return new d6(c)});
a=!!g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
$za(this,a);break;case "loungeScreenDisconnected":g.nb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
$za(this,!1);break;case "remoteConnected":var b=new d6(w6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1})||Sxa(this.u,b);
break;case "remoteDisconnected":b=new d6(w6(a.params.device));g.nb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":bAa(this,a);break;case "nowPlaying":dAa(this,a);break;case "onStateChange":cAa(this,a);break;case "onAdStateChange":eAa(this,a);break;case "onVolumeChanged":fAa(this,a);break;case "onSubtitlesTrackChanged":aAa(this,a);break;case "nowAutoplaying":gAa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":hAa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:f8("Unrecognized action: "+a.action)}};
g.h.dO=function(){if(this.A){var a=this.A;this.A=null;this.eb.videoId!=a&&k8(this,"getNowPlaying")}};
g.h.EF=function(){var a=3;this.ha()||(a=0,isNaN(this.dm())?c7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.h.ak=function(a){f8("Disconnecting with "+a);h8(this);this.S("beforeDisconnect",a);1==a&&p6();hza(this.o,a);this.dispose()};
g.h.CF=function(){var a=this.eb;this.A&&(a=this.eb.clone(),V7(a,this.A,a.index));return W7(a)};
g.h.rO=function(a){var b=new Q7(a);b.videoId&&b.videoId!=this.eb.videoId&&(this.A=b.videoId,g.Mo(this.G),this.G=g.Ko((0,g.x)(this.dO,this),5E3));var c=[];this.eb.listId==b.listId&&this.eb.videoId==b.videoId&&this.eb.index==b.index||c.push("remoteQueueChange");this.eb.playerState==b.playerState&&this.eb.volume==b.volume&&this.eb.muted==b.muted&&U7(this.eb)==U7(b)&&g.Ok(this.eb.o)==g.Ok(b.o)||c.push("remotePlayerChange");this.eb.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.h.ky=function(){var a=this.o.F.id,b=g.cb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.dm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.C)():NaN};
g.h.rF=function(){return this.B||"UNSUPPORTED"};
g.h.sF=function(){return this.F||""};
g.h.eP=function(){if(!isNaN(this.dm())){var a=this.o.u;g.xn(a.o);a.start()}};
g.h.lO=function(a,b){k8(this,a,b);Zza(this)};
e8.prototype.subscribe=e8.prototype.subscribe;e8.prototype.unsubscribeByKey=e8.prototype.hi;e8.prototype.getProxyState=e8.prototype.EF;e8.prototype.disconnect=e8.prototype.ak;e8.prototype.getPlayerContextData=e8.prototype.CF;e8.prototype.setPlayerContextData=e8.prototype.rO;e8.prototype.getOtherConnectedRemoteId=e8.prototype.ky;e8.prototype.getReconnectTimeout=e8.prototype.dm;e8.prototype.getAutoplayMode=e8.prototype.rF;e8.prototype.getAutoplayVideoId=e8.prototype.sF;e8.prototype.reconnect=e8.prototype.eP;
e8.prototype.sendMessage=e8.prototype.lO;g.r(l8,l7);g.h=l8.prototype;g.h.te=function(a){return this.Od.$_gs(a)};
g.h.contains=function(a){return!!this.Od.$_c(a)};
g.h.get=function(a){return this.Od.$_g(a)};
g.h.start=function(){this.Od.$_st()};
g.h.add=function(a,b,c){this.Od.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Od.$_r(a,b,c)};
g.h.Sq=function(a,b,c,d){this.Od.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Od.$_ubk(this.o[a]);this.o.length=0;this.Od=null;l7.prototype.X.call(this)};
g.h.iP=function(){this.S("screenChange")};
g.h.SL=function(){this.S("onlineScreenChange")};
u7.prototype.$_st=u7.prototype.start;u7.prototype.$_gspc=u7.prototype.jP;u7.prototype.$_gsppc=u7.prototype.AD;u7.prototype.$_c=u7.prototype.contains;u7.prototype.$_g=u7.prototype.get;u7.prototype.$_a=u7.prototype.add;u7.prototype.$_un=u7.prototype.Sq;u7.prototype.$_r=u7.prototype.remove;u7.prototype.$_gs=u7.prototype.te;u7.prototype.$_gos=u7.prototype.zD;u7.prototype.$_s=u7.prototype.subscribe;u7.prototype.$_ubk=u7.prototype.hi;var E8=null,D8=!1,m8=null,n8=null,C8=null,r8=[];g.r(F8,g.z);g.h=F8.prototype;g.h.X=function(){g.z.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.M();var a=this.Xa;a.unsubscribe("proxyStateChange",this.sB,this);a.unsubscribe("remotePlayerChange",this.Rm,this);a.unsubscribe("remoteQueueChange",this.gq,this);a.unsubscribe("previousNextChange",this.oB,this);a.unsubscribe("nowAutoplaying",this.kB,this);a.unsubscribe("autoplayDismissed",this.HA,this);this.Xa=this.module=null};
g.h.Mz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Xa.o)if(H8(this)){if(!Z7(this.Xa).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Z7(this.Xa).nb()?this.Xa.pause():this.Xa.play();break;case "control_play":this.Xa.play();break;case "control_pause":this.Xa.pause();break;case "control_seek":this.F.qz(c[0],c[1]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();J8(this,0===c?void 0:c);break;case "control_seek":J8(this,c[0]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.h.pK=function(a){this.G.KF(a)};
g.h.MO=function(a){this.Mz("control_subtitles_set_track",g.Pb(a)?null:a)};
g.h.IC=function(){var a=this.J.getOption("captions","track");g.Pb(a)||I8(this,a)};
g.h.Xb=function(a){this.module.Xb(a,this.J.getVideoData().lengthSeconds)};
g.h.YA=function(a){if(H8(this)){this.Xa.unsubscribe("remotePlayerChange",this.Rm,this);var b=Math.round(a.volume);a=!!a.muted;var c=Z7(this.Xa);if(b!==c.volume||a!==c.muted)this.Xa.setVolume(b,a),this.H.start();this.Xa.subscribe("remotePlayerChange",this.Rm,this)}};
g.h.sL=function(){g.Pb(this.A)||tAa(this,this.A);this.B=!1};
g.h.sB=function(a,b){this.u.stop();2===b&&this.GC()};
g.h.Rm=function(){if(H8(this)){this.o.stop();var a=Z7(this.Xa);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.ld=1;break;case 1082:case 1083:this.module.ld=0;break;default:this.module.ld=-1}switch(a.playerState){case 1081:case 1:G8(this,new g.HC(8));this.FC();break;case 1085:case 3:G8(this,new g.HC(9));break;case 1083:case 0:G8(this,new g.HC(2));this.F.stop();this.Xb(this.J.getVideoData().lengthSeconds);break;case 1084:G8(this,new g.HC(4));break;case 2:G8(this,new g.HC(4));
this.Xb(U7(a));break;case -1:G8(this,new g.HC(64));break;case -1E3:G8(this,new g.HC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=Z7(this.Xa).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,tAa(this,a));a=Z7(this.Xa);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.H.isActive()||this.lD()}else sAa(this)};
g.h.oB=function(){this.J.S("mdxpreviousnextchange")};
g.h.gq=function(){H8(this)||sAa(this)};
g.h.kB=function(a){isNaN(a)||this.J.S("mdxnowautoplaying",a)};
g.h.HA=function(){this.J.S("mdxautoplaycanceled")};
g.h.setAudioTrack=function(a){H8(this)&&this.Xa.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.h.seekTo=function(a,b){-1===Z7(this.Xa).playerState?J8(this,a):b&&this.Xa.seekTo(a)};
g.h.lD=function(){if(H8(this)){var a=Z7(this.Xa);this.events.kb(this.L);a.muted?this.J.mute():this.J.unMute();this.J.setVolume(a.volume);this.L=this.events.N(this.J,"onVolumeChange",this.YA)}};
g.h.FC=function(){this.o.stop();if(!this.Xa.ha()){var a=Z7(this.Xa);a.nb()&&G8(this,new g.HC(8));this.Xb(U7(a));this.o.start()}};
g.h.GC=function(){this.u.stop();this.o.stop();var a=this.Xa.B.getReconnectTimeout();2==this.Xa.o&&!isNaN(a)&&this.u.start()};g.r(K8,g.V);K8.prototype.dc=function(){this.o.show()};
K8.prototype.Qa=function(){this.o.hide()};
K8.prototype.u=function(){g.fO("https://support.google.com/youtube/answer/7640706")};
K8.prototype.A=function(){c6("mdx-manual-pairing-popup-ok");this.Qa()};g.r(L8,g.V);L8.prototype.dc=function(){this.o.show()};
L8.prototype.Qa=function(){this.o.hide()};
L8.prototype.u=function(){c6("mdx-privacy-popup-cancel");this.Qa()};
L8.prototype.A=function(){c6("mdx-privacy-popup-confirm");this.Qa()};g.r(M8,g.V);M8.prototype.u=function(a){vAa(this,a.state)};g.r(N8,g.CP);N8.prototype.B=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.ni=g.Bb(a,this.o,this),g.EP(this,(0,g.Jc)(a,this.o)),a=this.J.getOption("remote","currentReceiver"),this.Jb(this.o(a)),this.enable(!0)):this.enable(!1)};
N8.prototype.o=function(a){return a.key};
N8.prototype.Ef=function(a){return"cast-selector-receiver"===a?"Cast...":this.ni[a].name};
N8.prototype.Bd=function(a){g.CP.prototype.Bd.call(this,a);this.J.setOption("remote","currentReceiver",this.ni[a]);this.La.Qa()};g.r(O8,g.XL);g.h=O8.prototype;
g.h.create=function(){mAa(g.Qy(this.player.O()));this.subscriptions.push(g.Ro("yt-remote-before-disconnect",this.nK,this));this.subscriptions.push(g.Ro("yt-remote-connection-change",this.wM,this));this.subscriptions.push(g.Ro("yt-remote-receiver-availability-change",this.qB,this));this.subscriptions.push(g.Ro("yt-remote-auto-connect",this.uM,this));this.subscriptions.push(g.Ro("yt-remote-receiver-resumed",this.tM,this));this.subscriptions.push(g.Ro("mdx-privacy-popup-confirm",this.RN,this));this.subscriptions.push(g.Ro("mdx-privacy-popup-cancel",
this.QN,this));this.subscriptions.push(g.Ro("mdx-manual-pairing-popup-ok",this.QG,this));this.qB()};
g.h.load=function(){this.player.cancelPlayback();g.XL.prototype.load.call(this);this.pe=new F8(this,this.player,this.Xa);var a=(a=rAa())?a.currentTime:0;var b=B8()?new Y7(w8(),void 0):null;0==a&&b&&(a=U7(Z7(b)));0!==a&&this.Xb(a);uAa(this,this.Pb,this.Pb);g.DT(this.player.app,6)};
g.h.unload=function(){this.player.S("mdxautoplaycanceled");this.Ah=this.Bf;g.Ne(this.pe,this.Xa);this.Xa=this.pe=null;g.XL.prototype.unload.call(this);g.DT(this.player.app,5);P8(this)};
g.h.X=function(){g.So(this.subscriptions);g.XL.prototype.X.call(this)};
g.h.og=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.pe.Mz.apply(this.pe,[a].concat(g.la(c)))};
g.h.getAdState=function(){return this.ld};
g.h.GF=function(){return this.loaded?this.pe.suggestion:null};
g.h.cg=function(){return this.Xa?Z7(this.Xa).cg:!1};
g.h.hasNext=function(){return this.Xa?Z7(this.Xa).hasNext:!1};
g.h.Xb=function(a,b){this.dz=a||0;this.player.S("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.dz};
g.h.getProgressState=function(){var a=Z7(this.Xa),b=this.player.getVideoData();return{allowSeeking:g.O(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.kd():!a.isAdPlaying()&&this.player.kd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+S7(a):a.B,isAtLiveHead:1>=(a.A?a.u+S7(a):a.u)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.A?a.u+S7(a):a.u,seekableStart:0<a.C?a.C+
S7(a):a.C}};
g.h.nextVideo=function(){this.Xa&&this.Xa.nextVideo()};
g.h.lq=function(){this.Xa&&this.Xa.lq()};
g.h.nK=function(a){1===a&&(this.Fu=this.Xa?Z7(this.Xa):null)};
g.h.wM=function(){var a=B8()?new Y7(w8(),void 0):null;if(a){var b=this.Ah;this.loaded&&this.unload();this.Xa=a;this.Fu=null;b.key!==this.Bf.key&&(this.Ah=b,this.load())}else g.Me(this.Xa),this.Xa=null,this.loaded&&(this.unload(),(a=this.Fu)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,U7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.qB=function(){this.ni=[this.Bf].concat(oAa());var a=x8()||this.Bf;Q8(this,a);this.player.sa("onMdxReceiversChange")};
g.h.uM=function(){var a=x8();Q8(this,a)};
g.h.tM=function(){this.Ah=x8()};
g.h.RN=function(){this.Sm=!0;P8(this);D8=!1;E8&&z8(E8,1);E8=null};
g.h.QN=function(){this.Sm=!1;P8(this);Q8(this,this.Bf);this.Ah=this.Bf;D8=!1;E8=null;this.player.playVideo()};
g.h.QG=function(){this.lp=!0;P8(this);g.Ms("yt-remote-manual-pairing-warning-shown",!0,2592E3);D8=!1;E8&&z8(E8,1);E8=null};
g.h.fd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.ni;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?O7():Q8(this,b)),this.loaded?this.Ah:this.Bf;case "quickCast":return 2===this.ni.length&&"cast-selector-receiver"===this.ni[1].key?(b&&O7(),!0):!1}};
g.h.Av=function(){this.Xa.Av()};
g.h.Lf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.lM.remote=O8;})(_yt_player);
